language: ruby

# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4.1

  before_script:  
  - psql -c 'create database travis_ci_chitter_test;' -U postgres